// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package provider

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"internal"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "grid:provider:Deployment":
		r = &Deployment{}
	case "grid:provider:GatewayFQDN":
		r = &GatewayFQDN{}
	case "grid:provider:GatewayName":
		r = &GatewayName{}
	case "grid:provider:Kubernetes":
		r = &Kubernetes{}
	case "grid:provider:Network":
		r = &Network{}
	case "grid:provider:Scheduler":
		r = &Scheduler{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"grid",
		"provider",
		&module{version},
	)
}
