// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Threefold.Provider.Inputs
{

    public sealed class QSFSInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("cache", required: true)]
        public Input<int> Cache { get; set; } = null!;

        [Input("compression_algorithm")]
        public Input<string>? Compression_algorithm { get; set; }

        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("encryption_algorithm")]
        public Input<string>? Encryption_algorithm { get; set; }

        [Input("encryption_key", required: true)]
        public Input<string> Encryption_key { get; set; } = null!;

        [Input("expected_shards", required: true)]
        public Input<int> Expected_shards { get; set; } = null!;

        [Input("groups", required: true)]
        private InputList<Inputs.GroupArgs>? _groups;
        public InputList<Inputs.GroupArgs> Groups
        {
            get => _groups ?? (_groups = new InputList<Inputs.GroupArgs>());
            set => _groups = value;
        }

        [Input("max_zdb_data_dir_size", required: true)]
        public Input<int> Max_zdb_data_dir_size { get; set; } = null!;

        [Input("metadata", required: true)]
        public Input<Inputs.MetadataArgs> Metadata { get; set; } = null!;

        [Input("minimal_shards", required: true)]
        public Input<int> Minimal_shards { get; set; } = null!;

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("redundant_groups", required: true)]
        public Input<int> Redundant_groups { get; set; } = null!;

        [Input("redundant_nodes", required: true)]
        public Input<int> Redundant_nodes { get; set; } = null!;

        public QSFSInputArgs()
        {
        }
        public static new QSFSInputArgs Empty => new QSFSInputArgs();
    }
}
