version: 2
archives:
  - id: archive
    name_template: "{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
before:
  hooks:
    - make nodejs_sdk
builds:
  - binary: pulumi-resource-threefold
    dir: provider
    main: ./cmd/pulumi-resource-threefold/main.go
    ldflags:
      - -X github.com/threefoldtech/pulumi-threefold/provider/pkg/version.Version={{.Tag }}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: "arm64"
      - goos: windows
        goarch: "arm"
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
