// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Immutable;

namespace Pulumi.Threefold
{
    public static class Config
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "IDE1006", Justification = 
        "Double underscore prefix used to avoid conflicts with variable names.")]
        private sealed class __Value<T>
        {
            private readonly Func<T> _getter;
            private T _value = default!;
            private bool _set;

            public __Value(Func<T> getter)
            {
                _getter = getter;
            }

            public T Get() => _set ? _value : _getter();

            public void Set(T value)
            {
                _value = value;
                _set = true;
            }
        }

        private static readonly global::Pulumi.Config __config = new global::Pulumi.Config("threefold");

        private static readonly __Value<string?> _key_type = new __Value<string?>(() => __config.Get("key_type") ?? Utilities.GetEnv("") ?? "sr25519");
        /// <summary>
        /// The key type registered on substrate (ed25519 or sr25519).
        /// </summary>
        public static string? Key_type
        {
            get => _key_type.Get();
            set => _key_type.Set(value);
        }

        private static readonly __Value<string?> _mnemonic = new __Value<string?>(() => __config.Get("mnemonic") ?? Utilities.GetEnv("") ?? "");
        /// <summary>
        /// The mnemonic of the user. It is very secret.
        /// </summary>
        public static string? Mnemonic
        {
            get => _mnemonic.Get();
            set => _mnemonic.Set(value);
        }

        private static readonly __Value<string?> _network = new __Value<string?>(() => __config.Get("network") ?? Utilities.GetEnv("") ?? "");
        /// <summary>
        /// The network to deploy on.
        /// </summary>
        public static string? Network
        {
            get => _network.Get();
            set => _network.Set(value);
        }

        private static readonly __Value<string?> _relay_url = new __Value<string?>(() => __config.Get("relay_url"));
        /// <summary>
        /// The relay url, example: wss://relay.dev.grid.tf
        /// </summary>
        public static string? Relay_url
        {
            get => _relay_url.Get();
            set => _relay_url.Set(value);
        }

        private static readonly __Value<string?> _rmb_timeout = new __Value<string?>(() => __config.Get("rmb_timeout"));
        /// <summary>
        /// The timeout duration in seconds for rmb calls
        /// </summary>
        public static string? Rmb_timeout
        {
            get => _rmb_timeout.Get();
            set => _rmb_timeout.Set(value);
        }

        private static readonly __Value<string?> _substrate_url = new __Value<string?>(() => __config.Get("substrate_url"));
        /// <summary>
        /// The substrate url, example: wss://tfchain.dev.grid.tf/ws
        /// </summary>
        public static string? Substrate_url
        {
            get => _substrate_url.Get();
            set => _substrate_url.Set(value);
        }

    }
}
