# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_grid.config as __config
    config = __config
    import pulumi_grid.provider as __provider
    provider = __provider
else:
    config = _utilities.lazy_import('pulumi_grid.config')
    provider = _utilities.lazy_import('pulumi_grid.provider')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "grid",
  "mod": "provider",
  "fqn": "pulumi_grid.provider",
  "classes": {
   "grid:provider:Deployment": "Deployment",
   "grid:provider:GatewayFQDN": "GatewayFQDN",
   "grid:provider:GatewayName": "GatewayName",
   "grid:provider:Kubernetes": "Kubernetes",
   "grid:provider:Network": "Network",
   "grid:provider:Scheduler": "Scheduler"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "grid",
  "token": "pulumi:providers:grid",
  "fqn": "pulumi_grid",
  "class": "Provider"
 }
]
"""
)
