// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Grid.Provider.Outputs
{

    [OutputType]
    public sealed class Backend
    {
        public readonly string Address;
        public readonly string Namespace;
        public readonly string Password;

        [OutputConstructor]
        private Backend(
            string address,

            string @namespace,

            string password)
        {
            Address = address;
            Namespace = @namespace;
            Password = password;
        }
    }
}
