// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Grid.Provider.Outputs
{

    [OutputType]
    public sealed class Disk
    {
        public readonly string? Description;
        public readonly string Name;
        public readonly int Size;

        [OutputConstructor]
        private Disk(
            string? description,

            string name,

            int size)
        {
            Description = description;
            Name = name;
            Size = size;
        }
    }
}
