// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Threefold.Provider.Outputs
{

    [OutputType]
    public sealed class K8sNodeComputed
    {
        public readonly string Computed_ip;
        public readonly string Computed_ip6;
        public readonly string Console_url;
        public readonly string Ip;
        public readonly string Network_name;
        public readonly string Ssh_key;
        public readonly string Token;
        public readonly string Ygg_ip;

        [OutputConstructor]
        private K8sNodeComputed(
            string computed_ip,

            string computed_ip6,

            string console_url,

            string ip,

            string network_name,

            string ssh_key,

            string token,

            string ygg_ip)
        {
            Computed_ip = computed_ip;
            Computed_ip6 = computed_ip6;
            Console_url = console_url;
            Ip = ip;
            Network_name = network_name;
            Ssh_key = ssh_key;
            Token = token;
            Ygg_ip = ygg_ip;
        }
    }
}
