// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Threefold.Provider.Outputs
{

    [OutputType]
    public sealed class QSFSComputed
    {
        public readonly string Metrics_endpoint;

        [OutputConstructor]
        private QSFSComputed(string metrics_endpoint)
        {
            Metrics_endpoint = metrics_endpoint;
        }
    }
}
