// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Grid.Provider.Outputs
{

    [OutputType]
    public sealed class VMComputed
    {
        public readonly string Computed_ip;
        public readonly string Computed_ip6;
        public readonly string Console_url;
        public readonly string? Ip;
        public readonly string Ygg_ip;

        [OutputConstructor]
        private VMComputed(
            string computed_ip,

            string computed_ip6,

            string console_url,

            string? ip,

            string ygg_ip)
        {
            Computed_ip = computed_ip;
            Computed_ip6 = computed_ip6;
            Console_url = console_url;
            Ip = ip;
            Ygg_ip = ygg_ip;
        }
    }
}
