// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Threefold.Provider.Outputs
{

    [OutputType]
    public sealed class ZDBInput
    {
        public readonly string? Description;
        public readonly string? Mode;
        public readonly string Name;
        public readonly string Password;
        public readonly bool? Public;
        public readonly int Size;

        [OutputConstructor]
        private ZDBInput(
            string? description,

            string? mode,

            string name,

            string password,

            bool? @public,

            int size)
        {
            Description = description;
            Mode = mode;
            Name = name;
            Password = password;
            Public = @public;
            Size = size;
        }
    }
}
