// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class GatewayFQDN extends pulumi.CustomResource {
    /**
     * Get an existing GatewayFQDN resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): GatewayFQDN {
        return new GatewayFQDN(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'threefold:index:GatewayFQDN';

    /**
     * Returns true if the given object is an instance of GatewayFQDN.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is GatewayFQDN {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === GatewayFQDN.__pulumiType;
    }

    /**
     * The backends of the gateway proxy. must be in the format ip:port if tls_passthrough is set, otherwise the format should be http://ip[:port]
     */
    declare public readonly backends: pulumi.Output<string[]>;
    /**
     * The deployment ID
     */
    declare public /*out*/ readonly contract_id: pulumi.Output<number>;
    /**
     * The description of the virtual machine workload, optional with no restrictions
     */
    declare public readonly description: pulumi.Output<string | undefined>;
    /**
     * The fully qualified domain name of the deployed workload
     */
    declare public readonly fqdn: pulumi.Output<string>;
    /**
     * Gateway workload name.  This has to be unique within the deployment. It's required and cannot exceed 50 characters. Must contain only alphanumeric and underscore characters
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Network name to join, if backend IP is private
     */
    declare public readonly network_name: pulumi.Output<string | undefined>;
    /**
     * Mapping from each node to its deployment ID
     */
    declare public /*out*/ readonly node_deployment_id: pulumi.Output<{[key: string]: number}>;
    /**
     * The gateway's node ID
     */
    declare public readonly node_id: pulumi.Output<any>;
    /**
     * The name of the solution for created contract to be consistent across threefold tooling (project name in deployment metadata)
     */
    declare public readonly solution_type: pulumi.Output<string | undefined>;
    /**
     * TLS passthrough controls the TLS termination, if false, the gateway will terminate the TLS, if True, it will only be terminated by the backend service
     */
    declare public readonly tls_pass_through: pulumi.Output<boolean | undefined>;

    /**
     * Create a GatewayFQDN resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: GatewayFQDNArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.backends === undefined && !opts.urn) {
                throw new Error("Missing required property 'backends'");
            }
            if (args?.fqdn === undefined && !opts.urn) {
                throw new Error("Missing required property 'fqdn'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.node_id === undefined && !opts.urn) {
                throw new Error("Missing required property 'node_id'");
            }
            resourceInputs["backends"] = args?.backends;
            resourceInputs["description"] = args?.description;
            resourceInputs["fqdn"] = args?.fqdn;
            resourceInputs["name"] = args?.name;
            resourceInputs["network_name"] = args?.network_name;
            resourceInputs["node_id"] = args?.node_id;
            resourceInputs["solution_type"] = (args?.solution_type) ?? "";
            resourceInputs["tls_pass_through"] = args?.tls_pass_through;
            resourceInputs["contract_id"] = undefined /*out*/;
            resourceInputs["node_deployment_id"] = undefined /*out*/;
        } else {
            resourceInputs["backends"] = undefined /*out*/;
            resourceInputs["contract_id"] = undefined /*out*/;
            resourceInputs["description"] = undefined /*out*/;
            resourceInputs["fqdn"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["network_name"] = undefined /*out*/;
            resourceInputs["node_deployment_id"] = undefined /*out*/;
            resourceInputs["node_id"] = undefined /*out*/;
            resourceInputs["solution_type"] = undefined /*out*/;
            resourceInputs["tls_pass_through"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(GatewayFQDN.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a GatewayFQDN resource.
 */
export interface GatewayFQDNArgs {
    /**
     * The backends of the gateway proxy. must be in the format ip:port if tls_passthrough is set, otherwise the format should be http://ip[:port]
     */
    backends: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The description of the virtual machine workload, optional with no restrictions
     */
    description?: pulumi.Input<string>;
    /**
     * The fully qualified domain name of the deployed workload
     */
    fqdn: pulumi.Input<string>;
    /**
     * Gateway workload name.  This has to be unique within the deployment. It's required and cannot exceed 50 characters. Must contain only alphanumeric and underscore characters
     */
    name: pulumi.Input<string>;
    /**
     * Network name to join, if backend IP is private
     */
    network_name?: pulumi.Input<string>;
    /**
     * The gateway's node ID
     */
    node_id: any;
    /**
     * The name of the solution for created contract to be consistent across threefold tooling (project name in deployment metadata)
     */
    solution_type?: pulumi.Input<string>;
    /**
     * TLS passthrough controls the TLS termination, if false, the gateway will terminate the TLS, if True, it will only be terminated by the backend service
     */
    tls_pass_through?: pulumi.Input<boolean>;
}
