// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Scheduler extends pulumi.CustomResource {
    /**
     * Get an existing Scheduler resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Scheduler {
        return new Scheduler(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'threefold:index:Scheduler';

    /**
     * Returns true if the given object is an instance of Scheduler.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Scheduler {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Scheduler.__pulumiType;
    }

    declare public readonly certification_type: pulumi.Output<string | undefined>;
    declare public readonly city: pulumi.Output<string | undefined>;
    declare public readonly country: pulumi.Output<string | undefined>;
    declare public readonly dedicated: pulumi.Output<boolean | undefined>;
    declare public readonly domain: pulumi.Output<boolean | undefined>;
    declare public readonly farm_ids: pulumi.Output<number[] | undefined>;
    declare public readonly farm_name: pulumi.Output<string | undefined>;
    declare public readonly free_ips: pulumi.Output<number | undefined>;
    declare public readonly gpu_available: pulumi.Output<boolean | undefined>;
    declare public readonly gpu_device_id: pulumi.Output<string | undefined>;
    declare public readonly gpu_device_name: pulumi.Output<string | undefined>;
    declare public readonly gpu_vendor_id: pulumi.Output<string | undefined>;
    declare public readonly gpu_vendor_name: pulumi.Output<string | undefined>;
    declare public readonly has_gpu: pulumi.Output<boolean | undefined>;
    declare public readonly hru: pulumi.Output<number | undefined>;
    declare public readonly ipv4: pulumi.Output<boolean | undefined>;
    declare public readonly ipv6: pulumi.Output<boolean | undefined>;
    declare public readonly mru: pulumi.Output<number | undefined>;
    declare public readonly node_id: pulumi.Output<number | undefined>;
    declare public /*out*/ readonly nodes: pulumi.Output<number[]>;
    declare public readonly rentable: pulumi.Output<boolean | undefined>;
    declare public readonly rented: pulumi.Output<boolean | undefined>;
    declare public readonly sru: pulumi.Output<number | undefined>;
    declare public readonly twin_id: pulumi.Output<number | undefined>;
    declare public readonly wireguard: pulumi.Output<boolean | undefined>;
    declare public readonly ygg: pulumi.Output<boolean | undefined>;

    /**
     * Create a Scheduler resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: SchedulerArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["certification_type"] = args?.certification_type;
            resourceInputs["city"] = args?.city;
            resourceInputs["country"] = args?.country;
            resourceInputs["dedicated"] = args?.dedicated;
            resourceInputs["domain"] = args?.domain;
            resourceInputs["farm_ids"] = args?.farm_ids;
            resourceInputs["farm_name"] = args?.farm_name;
            resourceInputs["free_ips"] = args?.free_ips;
            resourceInputs["gpu_available"] = args?.gpu_available;
            resourceInputs["gpu_device_id"] = args?.gpu_device_id;
            resourceInputs["gpu_device_name"] = args?.gpu_device_name;
            resourceInputs["gpu_vendor_id"] = args?.gpu_vendor_id;
            resourceInputs["gpu_vendor_name"] = args?.gpu_vendor_name;
            resourceInputs["has_gpu"] = args?.has_gpu;
            resourceInputs["hru"] = args?.hru;
            resourceInputs["ipv4"] = args?.ipv4;
            resourceInputs["ipv6"] = args?.ipv6;
            resourceInputs["mru"] = args?.mru;
            resourceInputs["node_id"] = args?.node_id;
            resourceInputs["rentable"] = args?.rentable;
            resourceInputs["rented"] = args?.rented;
            resourceInputs["sru"] = args?.sru;
            resourceInputs["twin_id"] = args?.twin_id;
            resourceInputs["wireguard"] = args?.wireguard;
            resourceInputs["ygg"] = args?.ygg;
            resourceInputs["nodes"] = undefined /*out*/;
        } else {
            resourceInputs["certification_type"] = undefined /*out*/;
            resourceInputs["city"] = undefined /*out*/;
            resourceInputs["country"] = undefined /*out*/;
            resourceInputs["dedicated"] = undefined /*out*/;
            resourceInputs["domain"] = undefined /*out*/;
            resourceInputs["farm_ids"] = undefined /*out*/;
            resourceInputs["farm_name"] = undefined /*out*/;
            resourceInputs["free_ips"] = undefined /*out*/;
            resourceInputs["gpu_available"] = undefined /*out*/;
            resourceInputs["gpu_device_id"] = undefined /*out*/;
            resourceInputs["gpu_device_name"] = undefined /*out*/;
            resourceInputs["gpu_vendor_id"] = undefined /*out*/;
            resourceInputs["gpu_vendor_name"] = undefined /*out*/;
            resourceInputs["has_gpu"] = undefined /*out*/;
            resourceInputs["hru"] = undefined /*out*/;
            resourceInputs["ipv4"] = undefined /*out*/;
            resourceInputs["ipv6"] = undefined /*out*/;
            resourceInputs["mru"] = undefined /*out*/;
            resourceInputs["node_id"] = undefined /*out*/;
            resourceInputs["nodes"] = undefined /*out*/;
            resourceInputs["rentable"] = undefined /*out*/;
            resourceInputs["rented"] = undefined /*out*/;
            resourceInputs["sru"] = undefined /*out*/;
            resourceInputs["twin_id"] = undefined /*out*/;
            resourceInputs["wireguard"] = undefined /*out*/;
            resourceInputs["ygg"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Scheduler.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Scheduler resource.
 */
export interface SchedulerArgs {
    certification_type?: pulumi.Input<string>;
    city?: pulumi.Input<string>;
    country?: pulumi.Input<string>;
    dedicated?: pulumi.Input<boolean>;
    domain?: pulumi.Input<boolean>;
    farm_ids?: pulumi.Input<pulumi.Input<number>[]>;
    farm_name?: pulumi.Input<string>;
    free_ips?: pulumi.Input<number>;
    gpu_available?: pulumi.Input<boolean>;
    gpu_device_id?: pulumi.Input<string>;
    gpu_device_name?: pulumi.Input<string>;
    gpu_vendor_id?: pulumi.Input<string>;
    gpu_vendor_name?: pulumi.Input<string>;
    has_gpu?: pulumi.Input<boolean>;
    hru?: pulumi.Input<number>;
    ipv4?: pulumi.Input<boolean>;
    ipv6?: pulumi.Input<boolean>;
    mru?: pulumi.Input<number>;
    node_id?: pulumi.Input<number>;
    rentable?: pulumi.Input<boolean>;
    rented?: pulumi.Input<boolean>;
    sru?: pulumi.Input<number>;
    twin_id?: pulumi.Input<number>;
    wireguard?: pulumi.Input<boolean>;
    ygg?: pulumi.Input<boolean>;
}
